In [201]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [202]:
data=pd.read_csv(r"C:\Users\GOPESHWAR KUMAR\Document\SQL\Work\ML\loan_approval_dataset.csv")

In [203]:
data.head(2)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected

In [204]:
data.tail(2)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [205]:
data.shape

(4269, 13)

In [206]:
data.size

55497

In [207]:
data.info

<bound method DataFrame.info of       loan_id   no_of_dependents      education  self_employed   income_annum  \
0           1                  2       Graduate             No        9600000
1           2                  0   Not Graduate            Yes        4100000
2           3                  3       Graduate             No        9100000
3           4                  3       Graduate             No        8200000
4           5                  5   Not Graduate            Yes        9800000
...       ...                ...            ...            ...            ...
4264     4265                  5       Graduate            Yes        1000000
4265     4266                  0   Not Graduate            Yes        3300000
4266     4267                  2   Not Graduate             No        6500000
4267     4268                  1   Not Graduate             No        4100000
4268     4269                  1       Graduate             No        9200000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000
1         12200000           8           417                    2700000
2         29700000          20           506                    7100000
3         30700000           8           467                   18200000
4         24200000          20           382                   12400000
...            ...         ...           ...                        ...
4264       2300000          12           317                    2800000
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 13 columns]>

In [208]:
data.describe

<bound method NDFrame.describe of       loan_id   no_of_dependents      education  self_employed   income_annum  \
0           1                  2       Graduate             No        9600000
1           2                  0   Not Graduate            Yes        4100000
2           3                  3       Graduate             No        9100000
3           4                  3       Graduate             No        8200000
4           5                  5   Not Graduate            Yes        9800000
...       ...                ...            ...            ...            ...
4264     4265                  5       Graduate            Yes        1000000
4265     4266                  0   Not Graduate            Yes        3300000
4266     4267                  2   Not Graduate             No        6500000
4267     4268                  1   Not Graduate             No        4100000
4268     4269                  1       Graduate             No        9200000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000
1         12200000           8           417                    2700000
2         29700000          20           506                    7100000
3         30700000           8           467                   18200000
4         24200000          20           382                   12400000
...            ...         ...           ...                        ...
4264       2300000          12           317                    2800000
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 13 columns]>

In [209]:
data.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='str')

In [210]:
data.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [211]:
label=LabelEncoder()

In [226]:
data[" education"]=label.fit_transform(data[" education"])
data[" self_employed"]=label.fit_transform(data[" self_employed"])

In [227]:
data.head(3)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected

In [228]:
data.drop("loan_id",inplace=True,axis=1)

KeyError: "['loan_id'] not found in axis"

In [229]:
# ordinal=OrdinalEncoder()
# label=LabelEncoder()
data.head(2)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected

In [230]:
# x=data.iloc[: ,:-1]
# y=data.iloc[:,11]
x=data.drop(" loan_status",axis=1)
y=data[" loan_status"]

In [231]:
x

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [232]:
scale=StandardScaler()

In [233]:
scale.fit_transform(x)

array([[-0.2941017 , -0.99555917, -1.00728821, ...,  2.877289  ,
         0.83202837,  0.93030441],
       [-1.4735476 ,  1.00446064,  0.99276452, ..., -0.63192107,
        -0.69499321, -0.51593638],
       [ 0.29562125, -0.99555917, -1.00728821, ..., -0.10781827,
         1.99651964,  2.40731629],
       ...,
       [-0.2941017 ,  1.00446064, -1.00728821, ...,  1.69236092,
         0.3266831 ,  0.71490685],
       [-0.88382465,  1.00446064, -1.00728821, ..., -0.97372725,
        -0.11274758,  0.25334064],
       [-0.88382465, -0.99555917, -1.00728821, ...,  1.55563845,
         2.26017804,  2.16114764]], shape=(4269, 11))

In [234]:
x

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [235]:
y

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
Name:  loan_status, Length: 4269, dtype: str

In [236]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [237]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [238]:
model=GaussianNB()

In [239]:
model.fit(x_train,y_train)

GaussianNB()

In [240]:
model.predict(x_test)

array([' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Rejected', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Rejected', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Rejected', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Rejected',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Rejected',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Rejected', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Rejected', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Rejected', ' Rejected', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Rejected', ' Rejected', ' Rejected', ' Approved', ' Approved',
       ' Rejected', ' Approved', ' Approved', ' Approved', ' Rejected',
       ' Approved', ' Approved', ' Approved', ' Approved', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Rejected', ' Approved',
       ' Approved', ' Approved', ' Approved', ' Approved'], dtype='<U9')

In [241]:
model.score(x_test,y_test)

0.7716627634660421

In [242]:
model.score(x_train,y_train)

0.7654465592972182

In [ ]:
model.predict[[3,1,0,100000,50000,5,7]]

In [245]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved